### ISSUE TITLE
User gets added even if required input conditions not met

### ISSUE THREAD

**Issue by ritwizsinha** [dsciitpatna/sahaayak_server#9]
![image](https://user-images.githubusercontent.com/43509699/55686459-120be980-597f-11e9-8f9a-b3f5f6a5e556.png)
Here it shows that name is to short
![image](https://user-images.githubusercontent.com/43509699/55686470-34056c00-597f-11e9-9cc1-8402bed77952.png)
But in database its added

**Comment by deepanjan05** [comment]
The problem arises due to asynchronous nature of node.js . 
Solution: Move line 29 to 76 inside else block of if(!matched) of validation check
